// MainWindow.idl
import "OobSimulatorViewModel.idl";

namespace OobSimulator
{
[default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window
{
    MainWindow();

    OobSimulatorViewModel MainViewModel
    {
        get;
    };
}
} // namespace OobSimulator
