// MainWindow.idl

namespace OobSimulator
{
// clang-format off
[default_interface]
runtimeclass MainWindow : Microsoft.UI.Xaml.Window
// clang-format on
{
    MainWindow();
}
} // namespace OobSimulator
