// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace OobSimulator
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();

        Double NavViewCompactModeThresholdWidth
        { 
            get; 
        };
    }
}
