// OobSimulatorViewModel.idl
import "BindableBase.idl";
import "DelegateCommand.idl";
import "UwbSessionData.idl";

namespace OobSimulator
{
// clang-format off
[default_interface]
unsealed runtimeclass OobSimulatorViewModel : OobSimulator.BindableBase
// clang-format on
{
    OobSimulatorViewModel();
    UwbSessionData UwbSessionData
    {
        get;
    };
    Microsoft.UI.Xaml.Input.ICommand SetUwbSessionDataCommand
    {
        get;
    };
}
} // namespace OobSimulator