
import "BindableBase.idl";

namespace OobSimulator
{
    [bindable]
    [default_interface]
    runtimeclass SettingsPageViewModel : OobSimulator.BindableBase
    {
        SettingsPageViewModel();
    }
} // namespace OobSimulator
