# Workflow to generate official release builds.

name: Build [Official Release]

# Run on workflow dispatch to allow manual triggering of the workflow, and run
# on PRs to the release branches.
on:
  workflow_dispatch:
  pull_request:
    branches: [ release/** ]

jobs:
  build-official-release:
    name: build
    uses: ./.github/workflows/cmake.yml
    with:
      build-types: "[ 'debug', 'release' ]"
      analyze-codeql: true
      install: true
      package: true
      publish-artifacts: true
      preset-name: official-release
